# Use an official Node.js runtime as the base image
FROM node:alpine

# Set the working directory in the container to /app
WORKDIR /server


# Install json-server globally in the container
RUN npm install -g json-server@1.0.0-alpha.16

# Copy db.json (your database file) to the working directory
COPY data.json .

# Make port 4000 available outside the container
EXPOSE 3001

# Define the command to run json-server
CMD [ "json-server", "--watch", "data.json", "--port", "3001" ]
