version: '3.9'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     target: development
  #   command: pnpm dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:7.2-alpine3.18
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
